### ISSUE TITLE
git-annex issue

### ISSUE THREAD

**Issue by dlevitas** [ReproNim/reproin#34]
Hello,

I used pip to install heudiconv and datalad, and git clone to install git-annex. Each of these has been added to my path, but when I tried to run ```heudiconv -f reproin --bids --datalad -o OUTPUT --files INPUT``` on the phantom data, I got this error:

```
Traceback (most recent call last):
  File "/N/u/dlevitas/Carbonate/.local/bin/datalad", line 7, in <module>
    from datalad.cmdline.main import main
  File "/N/u/dlevitas/Carbonate/.local/lib/python3.6/site-packages/datalad/__init__.py", line 51, in <module>
    cfg = ConfigManager()
  File "/N/u/dlevitas/Carbonate/.local/lib/python3.6/site-packages/datalad/config.py", line 208, in __init__
    self.reload(force=True)
  File "/N/u/dlevitas/Carbonate/.local/lib/python3.6/site-packages/datalad/config.py", line 262, in reload
    stdout, stderr = self._run(run_args, log_stderr=True)
  File "/N/u/dlevitas/Carbonate/.local/lib/python3.6/site-packages/datalad/config.py", line 530, in _run
    out = self._runner.run(['git', 'config'] + args, **kwargs)
  File "/N/u/dlevitas/Carbonate/.local/lib/python3.6/site-packages/datalad/cmd.py", line 691, in run
    cmd, env=self.get_git_environ_adjusted(env), *args, **kwargs)
  File "/N/u/dlevitas/Carbonate/.local/lib/python3.6/site-packages/datalad/cmd.py", line 550, in run
    raise CommandError(text_type(cmd), msg, status, out[0], out[1])
datalad.support.exceptions.CommandError: CommandError: command '['git', 'config', '-z', '-l']' failed with exitcode 1
Failed to run ['git', 'config', '-z', '-l'] under None. Exit code=1. out= err=** base directory /gpfs/home/d/l/dlevitas/Carbonate/git-annex/standalone/linux/skel does not contain bin/git-annex
```

I'm having trouble debugging this, and was wondering if anyone could help?

Thanks,

Dan

**Comment by dlevitas** [comment]
I was actually able to reinstall git-annex [here](https://git-annex.branchable.com/install/Linux_standalone/) (x86-64 tarball) and add it to my $PATH, which fixed the issue

**Comment by yarikoptic** [comment]
Great that it all worked out ;-)
